---
name: MegaLinter

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0

      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/terraform@03986e6993ccf699a22451118520680b438e7d2a # v7.11.1
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          # GITHUB_STATUS_REPORTER only works if VALIDATE_ALL_CODEBASE is false!
          GITHUB_STATUS_REPORTER: true
          REPORTERS_MARKDOWN_TYPE: simple
          SHOW_ELAPSED_TIME: false
          SHOW_SKIPPED_LINTERS: true
